# Generated by Django 3.1.3 on 2020-11-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedido_item',
            new_name='PedidoItem',
        ),
    ]
